title: pytket examples

sphinx:
  config:
    html_show_copyright: false
    html_theme_options:
      navigation_with_keys: True
      logo:
        image_light: _static/Quantinuum_logo_black.png
        image_dark: _static/Quantinuum_logo_white.png


execute:
  # Exclude some examples from execution (these are still deployed as html pages)
  exclude_patterns: [".venv/*", "Boxes_QPE_example.ipynb", "Forest_portability_example.ipynb", "backends_example.ipynb", "qiskit_integration.ipynb", "comparing_simulators.ipynb", "expectation_value_example.ipynb", "pytket-qujax_heisenberg_vqe.ipynb", "spam_example.ipynb", "tket_benchmarking.ipynb", "entanglement_swapping.ipynb", "pytket-qujax-classification.ipynb"]
  timeout: 90    # The maximum time (in seconds) each notebook cell is allowed to run.

# Information about where the book exists on the web
repository:
  url: https://github.com/CQCL/pytket  # Notebook files are located in pytket/examples
  path_to_book: docs  # Optional path to your book, relative to the repository root
  branch: master  # Which branch of the repository should be used when creating links (optional)

# Add GitHub buttons to your book
# See https://jupyterbook.org/customize/config.html#add-a-link-to-your-repository
html:
  use_issues_button: true
  use_repository_button: true
